### ISSUE TITLE
TypeError: cb is not a function

### ISSUE THREAD

**Issue by Clan-Utility** [pantsel/sails-hook-amqp#1]
When AMQP tries to reconnect, it gives error:

    Sunday, November 12, 2017 2:03 PM verbose: [AMQP] channel closed
    [AMQP] reconnecting
    Sunday, November 12, 2017 2:03 PM verbose: [AMQP] connected
    /node_modules/sails-hook-amqp/lib/amqp.js:60
        cb(null,self);
        ^

    TypeError: cb is not a function

**Comment by pantsel** [comment]
@Clan-Utility , thanks for the feedback!
